# Generated by Django 4.1.2 on 2022-10-30 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('Programming', 'Programming'), ('Technical', 'Technical'), ('Fashion', 'Fashion'), ('Life style', 'Life style'), ('History', 'History')], max_length=100),
        ),
    ]
